<?php
// Prevent redirect loop
$_REQUEST['reauth'] = 1;

// Prevent logout caused by preventing redirect loop
add_filter('wp_login_errors', 'smsglobal_loginRedirectWorkaround');
global $reauth;
function smsglobal_loginRedirectWorkaround($errors)
{
    global $reauth;
    $reauth = false;

    return $errors;
}

// Login page unfortunately outputs directly, so we need to catch and ignore it
ob_start();
require dirname(__FILE__) . '/../../../../wp-login.php';
ob_end_clean();

// Need to reset the 'done' list so it re-prints the style sheets
global $wp_styles;
$wp_styles->done = array();

login_header() ?>
    <?php if(isset($error) && is_array($error) && $error['error'] == 1): ?>
    <div id="login_error">
        <strong><?php _e('ERROR', SMSGLOBAL_TEXT_DOMAIN); ?></strong>: <?php echo $error['error_msg']; ?>
        <br><br>
        <?php printf(
            __('If you are not able to receive verification code or do not have access to your phone. You can override this feature by setting %s to false in your %s file.', SMSGLOBAL_TEXT_DOMAIN),
            '<kbd>SMSGLOBAL_AUTH</kbd>',
            'wp-config.php'); ?>
    </div>
    <?php endif; ?>
    <form name="loginform" id="loginform" action="<?php echo esc_url( admin_url() ); ?>" method="post">
        <p><?php _e('An SMS has been sent to your phone for verification. Enter the code here to login.', SMSGLOBAL_TEXT_DOMAIN) ?></p>
        <p>
            <label for="user_login"><?php _e('SMS Code', SMSGLOBAL_TEXT_DOMAIN) ?><br />
                <input type="text" name="code" class="input" value="<?php echo esc_attr($user_login); ?>" size="20" /></label>
        </p>
        <p class="submit">
            <input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="<?php esc_attr_e('Log In'); ?>" />
            <a href="<?php echo wp_logout_url() ?>"><?php _e('Log out', SMSGLOBAL_TEXT_DOMAIN) ?></a>
        </p>
    </form>
<?php login_footer();
