<?php
// Prevent redirect loop
$_REQUEST['reauth'] = 1;

// Prevent logout caused by preventing redirect loop
add_filter('wp_login_errors', 'smsglobal_loginRedirectWorkaround');
global $reauth;
function smsglobal_loginRedirectWorkaround($errors)
{
    global $reauth;
    $reauth = false;

    return $errors;
}

// Login page unfortunately outputs directly, so we need to catch and ignore it
ob_start();
require dirname(__FILE__) . '/../../../../wp-login.php';
ob_end_clean();

// Need to reset the 'done' list so it re-prints the style sheets
global $wp_styles;
$wp_styles->done = array();

login_header() ?>
    <form name="loginform" id="loginform" action="<?php echo esc_url( admin_url() ); ?>" method="post">
        <p><?php echo Smsglobal_Utils::_('An SMS has been sent to your phone for verification. Enter the code here to login.') ?></p>
        <p>
            <label for="user_login"><?php echo Smsglobal_Utils::_('SMS Code') ?><br />
                <input type="text" name="code" class="input" value="<?php echo esc_attr($user_login); ?>" size="20" /></label>
        </p>
        <p class="submit">
            <input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="<?php esc_attr_e('Log In'); ?>" />
            <a href="<?php echo wp_logout_url() ?>"><?php echo Smsglobal_Utils::_('Log out') ?></a>
        </p>
    </form>
<?php login_footer();
